# Generated by Django 5.2.4 on 2025-07-24 19:30
# O script 0001_initial.py cria um modelo de dados, isto é, cria um "schema" de dados
# Por padrão, o django usado um banco de dados que já vem integrado ao python 3, chamado sqlite3; veja o arquivo de settings do projeto django
# O banco de dados é criado toda vez que o projeto é executado
# Arquivos de migrations são criados toda vez que os modelos de dados forem alterados; isso permite ao django gerenciar e manter um histórico das alterações feitas

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # chave primária; identificador
                ('nome', models.CharField(max_length=100, verbose_name='Nome')), # campo/atributo nome
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')), # campo/atributo preco
                ('estoque', models.IntegerField(verbose_name='Estoque')), # campo/atributo estoque
            ],
        ),
    ]
