# Generated by Django 5.2.4 on 2025-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    # Note a dependência: a segunda migration depende da primeira: na primeira temos um modelo de dados para o objeto Produto e agora temos um para Cliente
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
        ),
    ]
