"""
Django settings for Django1 project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

O arquivo settings.py em um projeto Django é o coração da configuração do seu projeto.
Ele contém todas as configurações necessárias para o funcionamento do seu aplicativo,
como informações do banco de dados, configurações de arquivos estáticos e muito mais.
É um arquivo de configuração em Python que define diversas opções para o seu projeto Django.
Ele permite que você personalize o comportamento do seu aplicativo, adaptando-o às suas necessidades específicas.
O arquivo settings.py geralmente está localizado na pasta raiz do seu projeto Django, junto com o arquivo manage.py.
"""

# Import dj-database-url at the beginning of the file.
import dj_database_url

from pathlib import Path

import whitenoise

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR: Define o caminho base do projeto.
# Em Python, resolve() é um metodo associado principalmente ao objeto pathlib.Path.
# Sua finalidade é resolver um caminho, ou seja, retorna a versão absoluta e canônica do caminho, removendo quaisquer segmentos e os links simbólicos seguintes.
# A aplicação do metodo parent duas vezes retorna o diretório 'C:/Users/jcogf/PycharmProjects'
# BASE_DIR é um objeto da classe WindowsPath.
# BASE_DIR é a raiz de nosso projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY: Uma chave secreta usada para segurança, como proteger contra ataques de falsificação de solicitação entre sites (CSRF).
SECRET_KEY = 'django-insecure-midi(^g940@=ro2v756ezi5ku@93x#q2e=jgu@z=nduxkq1#fp'

# SECURITY WARNING: don't run with debug turned on in production!
# Modo desenvolvimento: DEBUG = True
# Modo produção: DEBUG = False
DEBUG = False

# ALLOWED_HOSTS no Django é uma configuração de segurança encontrada no arquivo settings.py do seu projeto.
# É uma lista de strings que representam os nomes de host/domínio que sua aplicação Django tem permissão para servir.
# O principal objetivo de ALLOWED_HOSTS é prevenir ataques de cabeçalho HTTP Host. Esses ataques ocorrem quando um agente
# malicioso manipula o cabeçalho Host em uma solicitação HTTP para induzir um servidor web a servir conteúdo ou recursos de
# um domínio não intencional. Ao listar explicitamente os hosts permitidos, o Django garante que responderá apenas a solicitações
# com um cabeçalho Host correspondente a uma das entradas dessa lista, mitigando assim essa vulnerabilidade de segurança.
# Se uma solicitação chegar com um cabeçalho Host ausente em ALLOWED_HOSTS, o Django lançará uma exceção SuspiciousOperation,
# normalmente resultando em um erro 400 Bad Request.
ALLOWED_HOSTS = ['*']

# Application definition
# INSTALLED_APPS: Lista os aplicativos instalados no seu projeto.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'  # aplicação recém-criada
]

# MIDDLEWARE: Define a ordem de execução dos middlewares, que são componentes que atuam em requisições e respostas.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # configuração necessária para permitir que o Django (em parceria com a biblioteca whitenoise) processe arquivos estáticos quando o projeto estiver em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django1.urls'

# TEMPLATES: Configura os templates usados pelo seu projeto.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  # Diretório de templates: criamos um diretório de templates para cada aplicação

        # O que nós queremos dizer com a linha acima?
        # Estamos indicando para o projeto Django que, dentro de nossas aplicações (diretório core),
        # teremos um diretório chamado "templates", dentro do qual colocaremos nossos
        # templates (p. ex., nossas páginas html).

        'APP_DIRS': True,  # Quando 'APP_DIRS': True, queremos dizer que cada aplicação terá seu diretório de templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES: Configura as informações de conexão com o banco de dados, como tipo, nome do banco, usuário, senha, etc.
# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#        }
#    }
# Replace the SQLite DATABASES configuration with PostgreSQL:
DATABASES = {
    'default': dj_database_url.config(
    # Replace this value with your local database's connection string.
    default = 'postgresql://postgres:postgres@localhost:5432/mysite',
    conn_max_age = 600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# STATIC_URL e STATIC_ROOT: Configura o local onde os arquivos estáticos (CSS, JS, imagens, etc.) são servidos.
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# This setting informs Django of the URI path from which your static files will be served to users
# Here, they well be accessible at your-domain.onrender.com/static/... or yourcustomdomain.com/static/...
STATIC_URL = '/static/'
# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = Path(BASE_DIR / 'staticfiles')
    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Em um projeto Django podemos ter várias aplicações; durante o desenvolvimento, os arquivos estáticos ficarão salvos dentro de um diretório chamado static, para cada aplicação.
# Contudo, quando publicamos o projeto, nós executamos um comando, o qual irá coletar todos os arquivos estáticos dentro de cada diretório static dentro de cada aplicação.
# Um tal comando "depositará" todos os arquivos estáticos coletados centralizando-os no diretório staticfiles.
# Nota:
# Modo desenvolvimento: DEBUG = True
# Modo produção: DEBUG = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = 'index'  # Após o logout redireciona para o diretório raiz da aplicação
